# setup
setup: selflabel

# ema
use_ema: False

# Threshold
confidence_threshold: 0.1

# Criterion
criterion: confidence-cross-entropy
criterion_kwargs:
   apply_class_balancing: True
   entropy_weight: 500.0

# Model
backbone: resnet18
num_heads: 1

# Dataset
train_db_name: hint
val_db_name: hint
num_classes: 16

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 32
   # random_resized_crop:
   #   size: 32
   #   scale: [0.2, 1.0]
   normalize:
      mean: 0
      std: 1
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: 0
      std: 1

# Hyperparameters
epochs: 50
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
batch_size: 1000
num_workers: 8

# Scheduler
scheduler: constant
